const Engine = Matter.Engine;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
const World = Matter.World;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
const Bodies = Matter.Bodies;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
const Body = Matter.Body;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
function preload(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
function setup(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	createCanvas(1400,700);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	engine = Engine.create();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	world = engine.world;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 ground = new Ground(width/2,675,1400,20)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin1 = new Dustbin(1100,591,20,150)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin2 = new Dustbin(1300,591,20,150)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin3 = new Dustbin(1200,657,180,20)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 ball = new Ball(200,680)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 Engine.run(engine);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
function draw(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  rectMode(CENTER);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
background(0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 ground.display()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin1.display()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin2.display()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 bin3.display()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 ball.display()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
function keyPressed(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	if(keyCode === UP_ARROW ){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		Matter.Body.applyForce(ball.body,ball.body .position,{x:85,y:-85})                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                                                                                               